openapi: 3.0.0
info:
  title: Coffee API
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /coffee:
    get:
      summary: Pobierz listę kaw
      responses:
        "200":
          description: Lista dostępnych kaw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Coffee"
components:
  schemas:
    Coffee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        origin:
          type: string
